### ISSUE TITLE
Which codes indicate that a board always reSignOns after it sends packets out ?

### ISSUE THREAD

**Issue by paulyu12** [gujianxiao/ndn-lite-application-for-nRF52840-BLE_version#5]
1. The codes on the board only calls sign_on_basic_client_nrf_sdk_ble_construct once. 
2. I know that before the board sends extended advertising messages, it disconnect with the Android, but after the board sends extended advertising messages, it does not call any function for signing on explicitly.
4. Is it that the Android app sends the bootstrap response proactively, which trigger the callback on the board ? 

Can you tell me which codes indicate how the board signs on the Android phone after sending packets out ? Thanks.

**Comment by paulyu12** [comment]
I think the board tries to sign on again because after the board finishes send packets out, the led_3 sometimes (not always) blinks.

**Comment by peurpdapeurp** [comment]
Ah yes you are correct. The board does not explicitly try to reconnect with the Android phone after it disconnects to send out an extended advertisement BLE message, it is the Android phone which proactively scans for the board and then connects to it. This is described in the ndn-lite security bootstrapping wiki page in the figure of section 3.a.iii

**Comment by peurpdapeurp** [comment]
If you are wondering what code on Android phone side makes it proactively reconnect, it is done by the BLEUnicastConnectionMaintainer object, the code for which is here: https://github.com/gujianxiao/NDN-IoT-Android/blob/98cee5d30bc0ca05034e31734cf0b25a35ab8ce3/ndn_lite_support_library/src/main/java/NDNLiteSupport/BLEUnicastConnectionMaintainer/BLEUnicastConnectionMaintainer.java

You may have noticed that the code in the MainActivity of the example heavily stresses that you must make a BLEUnicastConnectionMaintainer object and initialize it, or else the SecureSignOnController object and BLEFace object will not work, and this is the reason why; if the phone does not proactively try to reconnect with the board after it disconnects to send out extended advertisement, the board will never be able to send BLE messages to the phone again.

The reason for this is because both of the Android phones we have been doing testing on (the Google Pixel 2 and Nexus 5) cannot detect BLE 5.0 extended advertisements. Unfortunately, even though the Google Pixel 2 claims to support BLE 5.0, it can actually only send but not receive BLE 5.0 extended advertisements. So this is our temporary workaround, until more Android devices that can actually detect BLE 5.0 extended advertisements can be found.

(I tried to explain all of this in the Secure Bootstrapping wiki page of the ndn-lite repository (https://github.com/named-data-iot/ndn-lite/wiki/Security-Bootstrapping), but if it was not clear or you think the wiki page should be updated, please let me know and I will do my best to improve it.)

**Comment by paulyu12** [comment]
Thanks for reply.

I am more interested in why LED_3 blinking after the phone reconnects to the board. Is function on_sign_on_completed called ? How does SSP run HERE ? It seems that not the board sending the bootstrapping request packet first to start SSP ?

Is it that when connection state changes, the controller calls respondToBootstrappingRequest directly to trigger SSP ?  Maybe my understanding is wrong.
![截图](https://user-images.githubusercontent.com/14888724/56866667-736b2980-6a0e-11e9-98cb-acbb44694c8b.PNG)

**Comment by peurpdapeurp** [comment]
blink_led(3) is actually called in several places in the nRF52840 BLE example, three places to be precise:

1) When a schema interest is received (this is when another board sends an interest to change this board's trust policy, it is a kind of "toy demonstration", since the board does not check the signature on this interest in any way, but it's just an example of taking different actions depending on the interest name)
2)  When a sign-on completes successfully
3) Just before the main loop, after the board has initialized successfully (but may have not completed the sign-on yet)

**Comment by peurpdapeurp** [comment]
Ah I am sorry, after looking at your issue again I'm starting to realize that none of those different places really explains the behavior you're describing. I'm doing some testing right now to try and find a better answer.

EDIT: Actually, I think that I will just put this issue on hold for now. My reasoning is that I am going to be overhauling the BLE example as soon as this issue (https://redmine.named-data.net/issues/4925) gets resolved.

**Comment by paulyu12** [comment]
Yes, maybe you'll find the behavior when you redo the example test. (eg. Board 2 blinks LED_3 after it sends Interest of /NDN-IoT/Board1/SD_LED/ON )

p.s. Edward Lu has found there isn't a bug about #Task4925(https://redmine.named-data.net/issues/4925).

**Comment by peurpdapeurp** [comment]
Ah yes, I am Edward Lu; I found through discussion with my labmates that there isn't actually a bug in jndn, it is just that the ndn-lite code does not correctly ignore an older version of the NDN packet format (which used to have a tlv block with type 0x09).

I am working on fixing the ndn-lite bug and fixing the example now.
